services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: takwria
      POSTGRES_PASSWORD: takwria
      POSTGRES_DB: takwria_dev
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - takwria_db_data:/var/lib/postgresql/data

  db_test:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: takwria
      POSTGRES_PASSWORD: takwria
      POSTGRES_DB: takwria_test
    ports:
      - "127.0.0.1:5433:5432"

volumes:
  takwria_db_data:
